/*----- PROTECTED REGION ID(EncTest.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        EncTest.cpp
//
// description : C++ source for the EncTest class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               EncTest are implemented in this file.
//
// project :     encoded attr test
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <EncTest.h>
#include <EncTestClass.h>

/*----- PROTECTED REGION END -----*/	//	EncTest.cpp

/**
 *  EncTest class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  myimage  |  Tango::DevEncoded	Scalar
//================================================================

namespace EncTest_ns
{
/*----- PROTECTED REGION ID(EncTest::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	EncTest::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : EncTest::EncTest()
 *	Description : Constructors for a Tango device
 *                implementing the classEncTest
 */
//--------------------------------------------------------
EncTest::EncTest(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(EncTest::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::constructor_1
}
//--------------------------------------------------------
EncTest::EncTest(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(EncTest::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::constructor_2
}
//--------------------------------------------------------
EncTest::EncTest(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(EncTest::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : EncTest::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void EncTest::delete_device()
{
	DEBUG_STREAM << "EncTest::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(EncTest::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::delete_device
	delete[] attr_myimage_read;
}

//--------------------------------------------------------
/**
 *	Method      : EncTest::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void EncTest::init_device()
{
	DEBUG_STREAM << "EncTest::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(EncTest::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::init_device_before
	
	//	No device property to be read from database
	
	attr_myimage_read = new Tango::DevEncoded[1];
	/*----- PROTECTED REGION ID(EncTest::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::init_device
}


//--------------------------------------------------------
/**
 *	Method      : EncTest::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void EncTest::always_executed_hook()
{
	DEBUG_STREAM << "EncTest::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(EncTest::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : EncTest::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void EncTest::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "EncTest::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(EncTest::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute myimage related method
 *	Description: 
 *
 *	Data type:	Tango::DevEncoded
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void EncTest::read_myimage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "EncTest::read_myimage(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(EncTest::read_myimage) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_myimage_read);
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::read_myimage
}

//--------------------------------------------------------
/**
 *	Method      : EncTest::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void EncTest::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(EncTest::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : EncTest::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void EncTest::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(EncTest::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::add_dynamic_commands
}

/*----- PROTECTED REGION ID(EncTest::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	EncTest::namespace_ending
} //	namespace
