/*----- PROTECTED REGION ID(EncTestStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        EncTestStateMachine.cpp
//
// description : State machine file for the EncTest class
//
// project :     encoded attr test
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <EncTest.h>

/*----- PROTECTED REGION END -----*/	//	EncTest::EncTestStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace EncTest_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : EncTest::is_myimage_allowed()
 *	Description : Execution allowed for myimage attribute
 */
//--------------------------------------------------------
bool EncTest::is_myimage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for myimage attribute in read access.
	/*----- PROTECTED REGION ID(EncTest::myimageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EncTest::myimageStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(EncTest::EncTestStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	EncTest::EncTestStateAllowed.AdditionalMethods

}	//	End of namespace
